#!/usr/bin/env python3
"""Writes a .env with freshly generated secrets.

Every secret in .env.example is required and has no fallback, so filling one in
by hand is now a prerequisite for starting the stack. This generates them:

    python security/generate_env.py

Refuses to overwrite an existing .env unless --force is given.

Regenerating secrets for a stack that has already run is not free: Postgres
only applies POSTGRES_PASSWORD when it initializes an empty data directory,
so a new password here will not match the one already baked into the
`postgres-db-volume` Docker volume - every Airflow component will fail to
connect with "password authentication failed" until that volume is dropped.
ACCOUNT_TOKEN_PEPPER has the same kind of consequence: existing rows in
vault.account_tokens were tokenized with the old pepper, so a new one makes
previously ingested account_ids produce different tokens than before, which
breaks the deterministic-token guarantee the gold/silver relationship test
relies on. --force prints a reminder about both.
"""
from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path

from cryptography.fernet import Fernet

REPO_ROOT = Path(__file__).resolve().parent.parent

TEMPLATE = """\
# Generated by security/generate_env.py - do not commit.
AIRFLOW_UID={uid}

POSTGRES_USER=airflow
POSTGRES_DB=airflow
POSTGRES_PASSWORD={postgres_password}

_AIRFLOW_WWW_USER_USERNAME=airflow
_AIRFLOW_WWW_USER_PASSWORD={ui_password}

AIRFLOW__CORE__FERNET_KEY={fernet_key}
AIRFLOW__API_AUTH__JWT_SECRET={jwt_secret}

GF_SECURITY_ADMIN_PASSWORD={grafana_password}

ACCOUNT_TOKEN_PEPPER={token_pepper}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=REPO_ROOT / ".env")
    parser.add_argument("--force", action="store_true", help="overwrite an existing file")
    args = parser.parse_args()

    if args.output.exists() and not args.force:
        print(f"{args.output} already exists - pass --force to overwrite", file=sys.stderr)
        return 1

    overwriting = args.output.exists() and args.force

    import os

    content = TEMPLATE.format(
        uid=os.getuid(),
        postgres_password=secrets.token_urlsafe(24),
        ui_password=secrets.token_urlsafe(18),
        fernet_key=Fernet.generate_key().decode(),
        jwt_secret=secrets.token_urlsafe(32),
        grafana_password=secrets.token_urlsafe(18),
        token_pepper=secrets.token_urlsafe(32),
    )

    args.output.write_text(content)
    args.output.chmod(0o600)
    print(f"wrote {args.output} (mode 600)")
    print("Airflow UI and Grafana passwords are in that file.")

    if overwriting:
        print(
            "\n"
            "You overwrote an existing .env. If Postgres has already been initialized\n"
            "with the old POSTGRES_PASSWORD (i.e. you've run `docker compose up` before),\n"
            "every Airflow component will now fail with 'password authentication failed'\n"
            "until you drop its volume and let it reinitialize:\n"
            "\n"
            "    docker compose down -v && docker compose up airflow-init && docker compose up -d --wait\n"
            "\n"
            "That only removes Airflow's own metadata DB - ./data and ./airflow/dags are\n"
            "host bind mounts and are untouched.\n"
            "\n"
            "The new ACCOUNT_TOKEN_PEPPER also means any account_id ingested before this\n"
            "point will tokenize differently than it did before - fine for a demo, but\n"
            "worth knowing if you're comparing runs.",
            file=sys.stderr,
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
